### ISSUE TITLE
Implement a tab component and an associated MDX extension.

### ISSUE THREAD

**Issue by SilasBerger** [SilasBerger/teaching-website#16]
See `feature/tabs-component` for a first approach.

The MDX syntax should look about as follows:
```mdx
# Instructions
Here are the instructions for each operating system.

::Tabs
:Tab :mdi-microsoft-windows: Windows
This is some text about Windows.

:Tab :mdi-apple: macOS
This is some text about macOS.

:Tab :mdi-linux: Linux
<details>
  <summary>See Linux instructions...</summary>
  <div>The instructions for Linux.</div>
</details>

::EndTabs
```

**Comment by SilasBerger** [comment]
As for the visual design of the tab container, this is what it might look like:
<img width="848" alt="image" src="https://github.com/SilasBerger/teaching-website/assets/8812237/57853130-5569-442b-a136-0051c05d0a65">

**Comment by lebalz** [comment]
Suggestion: usage of docusaurus' tab components and then swizzling the components/styles as needed...? https://docusaurus.io/docs/markdown-features/tabs

**Comment by SilasBerger** [comment]
> Suggestion: usage of docusaurus' tab components and then swizzling the components/styles as needed...? https://docusaurus.io/docs/markdown-features/tabs

Didn't know they already had that 😆  That's definitely the better solution, thanks!
